name: Deploy App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 src/ tests/

    - name: Run tests
      run: pytest

    - name: Deploy (example)
      if: success()
      run: echo "Tutaj dodaj polecenie deploya – SSH, webhook lub Railway CLI"
